# Generated by Django 5.0.7 on 2024-08-08 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_blog_contact_remove_project_service_tag_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="client",
            old_name="user",
            new_name="name",
        ),
    ]
