# Generated by Django 5.0.7 on 2024-08-08 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_rename_user_client_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="image",
            field=models.ImageField(blank=True, upload_to="blog_images/"),
        ),
    ]
